name: Build and Deploy to Demo Repo

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/screenshot.*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEMO_REPO_TOKEN }}
        with:
          source-directory: 'dist'
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: 'life-game-demo'
          user-email: nicolachoquet06250@gmail.com
          target-branch: main
